name: Publish to npm
on:
  push:
    branches:
      - master
    paths:
      - 'package.json'
jobs:
  test:
    uses: ./.github/workflows/test.yml
  get-version:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}
      last_version: ${{ steps.last_version.outputs.version }}
      token_exists: ${{ steps.check_token.outputs.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 50
      - name: Get current version from package.json
        id: current_version
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"
      - name: Get the version from the last push (if available)
        id: last_version
        run: |
          if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ]; then
            echo "version=" >> "$GITHUB_OUTPUT"
          else
            git fetch --no-tags --depth=1 origin ${{ github.event.before }}
            echo "version=$(git show ${{ github.event.before }}:package.json | jq -r .version)" >> "$GITHUB_OUTPUT"
          fi
      - name: Check if NPM_TOKEN exists
        id: check_token
        run: |
          if [ -n "${{ secrets.NPM_TOKEN }}" ]; then
            echo "token=true" >> "$GITHUB_OUTPUT"
          else
            echo "token=false" >> "$GITHUB_OUTPUT"
          fi
  npm-publish:
    needs:
      - test
      - get-version
    runs-on: ubuntu-latest
    if: needs.get-version.outputs.current_version != needs.get-version.outputs.last_version && needs.get-version.outputs.token_exists == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build-npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
